 
name: CMake

on:
  push:
    branches: [task5]
  pull_request:
    branches: [task5, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2

    - name: Build
      run: |
        cd task5
        mkdir 3rdparty
        cd 3rdparty
        git clone https://github.com/google/googletest.git
        mv googletest weird_name
        mv weird_name/* .
        rm -r weird_name
        cd ..
        mkdir build
        cd build
        cmake ..
        make
        cd ..
        cd ..
    
    - name: Test
      uses: akhtyamovpavel/ActionGtestReport@v0.0.9
      with:
        exec-path:  task5/bin/CTestExe
        report-path: task5/report.xml
        working-directory: task5
